//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_64132985.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCustomerDetail
    {
        public string OrderDetailID { get; set; }
        public int Quantity { get; set; }
        public string ProductID { get; set; }
        public string OrderID { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
    
        public virtual OrderCustomer OrderCustomer { get; set; }
        public virtual Product Product { get; set; }
    }
}
