//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_64132985.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderCustomer()
        {
            this.OrderCustomerDetails = new HashSet<OrderCustomerDetail>();
        }
    
        public string OrderID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CustomerID { get; set; }
        public string EmployeeID { get; set; }
        public string Status { get; set; }
        public string VoucherID { get; set; }
        public string PhoneNumber { get; set; }
        public string Addr { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCustomerDetail> OrderCustomerDetails { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
